### ISSUE TITLE
Event 'wrong_answer' is not reported

### ISSUE THREAD

**Issue by KirillMakarov** [StepicOrg/stepik-android-adaptive#1]
Because of extra check here:
https://github.com/StepicOrg/stepik-android-adaptive/blob/fc5059213cbdd54483873fd3438b37fdfc0d2ded/app/src/main/java/org/stepik/android/adaptive/pdd/ui/fragment/CardsFragment.java#L298

**Comment by eadm** [comment]
fixed in https://github.com/StepicOrg/stepik-android-adaptive/commit/7ab3bdd48792afaedc948ef689b7a983ba38eda5
